language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- flake8
deploy:
  api_key:
    secure: O6oWaorX8A4CMOaTUVbCneR17U4JZbBa3sYAO3NQxH/p0CRpIHeTfF1QBxKkTyUZUQdkctp3viOaNsuoG+XhmnvvYlD6upB1Dfi7gdLIu67j88Uu6d9nxKRHUX/YkKZzp8nIKmGB/qyjWQm/S7NeYCWGCusWV8fgDaLBNTWQ1HYzaVzANrO6n3oCACp2rDUHMsA0jWPpe0d2Rjm5iTtOxl2+9/ESdrzhaYqOmTOKvel17FLlkw7WrQMZAPCJi0knOMu1pw01FfOHOuHUtLT1L4ilj/G7RianLbI5MgsvXsoZRF4I76pG13hgl1QjWwGS5ZQjU9N6R3jFGwQ+fm4oY6Tt33cPyAZMFp6XYwick5CmzQVCODa4NGvlcIOkoWdqgN2KC8MEDCFrF27SlsFZjDjj+qsTM13NFdI4yJH/W35y7PZKMPzixfGwPd8KcXRcrzik6Aa6vThAwjKGhRa9j9yuvML49MSe87DJjIgBN180Lvg4UrhNKcYhjeJ+jqalnVYulAs9qNR1SlJYvPhgsBdI2jf9gSwF9uTQ3j0hSG9NQhEnv/n5LlIlbm2MWk7XLLpc4pbKZ7384N/LGrrGgKTfQ6UyJxsAUOqlgJj/0ZtI8Bwl/crwFMQRFXUCVRnjM0CqjWcGZ4V6KodYAsPu7aItfDPctkGyxt52vFrTBNU=
  on: master
  app: kinhank